# Directorio raíz del Firmware v3 (subir 3 niveles ahora)
MUJU_PATH = ../../../

# Directorios que contienen el código fuente (.c)
SRCS_DIRS = $(PROJ_PATH)/Core/Src

# Incluimos el motor principal de compilación
include $(MUJU_PATH)/project.mk